name: '${name}'
version: '${version}'
description: "Adds two custom potion bottles that can be used to teleport between worlds."
main: tech.simonwalker.dimensionhop.PortalBottlesPlugin
api-version: 1.18
authors: [ simondoesstuff ]
depend: [ kotlin-stdlib ]